### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by luji12311** [python-hhx/Competition#1]
Traceback (most recent call last):
  File "E:\project\Competition\shuxuntwo\predict.py", line 153, in <module>
    for image in tqdm(testloader):
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\project\Competition\shuxuntwo\predict.py", line 96, in __getitem__
    image = self._preprocess_first(image_file)
  File "E:\project\Competition\shuxuntwo\predict.py", line 31, in _preprocess_first
    image = Image.open(img_file)
  File "D:\Anaconda3\envs\yolov5\lib\site-packages\PIL\Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: '/'

**Comment by luji12311** [comment]
在使用test时候

**Comment by python-hhx** [comment]
你好，你看上上去更像的路径对应的权限问题，可能你对应的这个电脑用户账号在该路径下没有读取权限。







At 2024-06-26 17:39:48, "luji12311" ***@***.***> wrote:

Traceback (most recent call last):
File "E:\project\Competition\shuxuntwo\predict.py", line 153, in
for image in tqdm(testloader):
File "D:\Anaconda3\envs\yolov5\lib\site-packages\tqdm\std.py", line 1181, in iter
for obj in iterable:
File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 628, in next
data = self._next_data()
File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data_utils\fetch.py", line 58, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "D:\Anaconda3\envs\yolov5\lib\site-packages\torch\utils\data_utils\fetch.py", line 58, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "E:\project\Competition\shuxuntwo\predict.py", line 96, in getitem
image = self._preprocess_first(image_file)
File "E:\project\Competition\shuxuntwo\predict.py", line 31, in _preprocess_first
image = Image.open(img_file)
File "D:\Anaconda3\envs\yolov5\lib\site-packages\PIL\Image.py", line 3247, in open
fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: '/'
